[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@openzeppelin-v5.0.2/=singleton-paymaster/lib/openzeppelin-contracts-v5.0.2/",
    "@openzeppelin-v4.8.3/=singleton-paymaster/lib/openzeppelin-contracts-v4.8.3/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@account-abstraction-v7/=singleton-paymaster/lib/account-abstraction-v7/contracts/",
    "@account-abstraction-v6/=singleton-paymaster/lib/account-abstraction-v6/contracts/",
    "@ensdomains/=lib/ens-contracts/contracts/",
    "solady/=singleton-paymaster/lib/solady/src/",
    "singleton-paymaster/=singleton-paymaster/",
]

[profile.test]
verbosity = 3
gas_reports = ["SuperPaymasterV0_7"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
